---
# needed for k0sctl (auto login and sudo)
- name: Setup login with ssh and with sudo password
  hosts: k0s
  tasks:
    - name: Creates directory .ssh
      ansible.builtin.file:
        path: /home/opvolger/.ssh
        state: directory
        owner: opvolger
        group: opvolger
        mode: '0700'

    - name: Copy id_rsa.pub to authorized_keys
      ansible.builtin.copy:
        src: "/home/opvolger/.ssh/id_rsa.pub"
        dest: "/home/opvolger/.ssh/authorized_keys"
        owner: opvolger
        group: opvolger
        mode: '0600'

    - name: User Opvolger doesn't need password for sudo
      become: true
      ansible.builtin.blockinfile:
        state: present
        insertafter: EOF
        dest: /etc/sudoers
        content: |
          opvolger ALL=(ALL) NOPASSWD: ALL

# samba setup for persistent volume with samba
- name: Setup for samba
  become: true
  hosts: samba
  tasks:
    - name: Setup samba server
      ansible.builtin.include_tasks: tasks/k0s_setup_samba.yaml

  handlers:
    - name: Restart samba
      ansible.builtin.systemd:
        name: smb
        state: restarted

    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded

- name: Setup for all or servers
  become: true
  hosts: k0s
  tasks:

    - name: Server and node install packages
      ansible.builtin.include_tasks: tasks/k0s_install_stuff.yaml

    - name: Server and node firewall
      ansible.builtin.include_tasks: tasks/k0s_setup_firewall.yaml

  handlers:
    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded

- name: Setup network with correct ip!
  ansible.builtin.import_playbook: k0s_setup_network.yaml
