---
- name: Setup arch and k0s_binary_path variables
  hosts: k0s
  tasks:
    - name: Debug k0s_binary_path_without_arch
      ansible.builtin.debug:
        var: k0s_binary_path_without_arch

    - name: Get DEB architecture
      ansible.builtin.shell: dpkg --print-architecture
      changed_when: false
      register: deb_architecture

    - name: Set k0sBinaryPath variable
      ansible.builtin.set_fact:
        k0s_binary_path: "{{ k0s_binary_path_without_arch }}{{ deb_architecture.stdout }}"
        arch: "{{ deb_architecture.stdout }}"

    - name: Debug k0s_binary_path
      ansible.builtin.debug:
        var: k0s_binary_path

- name: Setup all controller nodes
  hosts: localhost
  tasks:

    - name: Get current user info
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        state: present
      register: user_info
      check_mode: true  # Important, otherwise user will be created

    - name: Create k0sctl.yaml
      ansible.builtin.template:
        src: templates/k0sctl.yaml
        dest: "{{ playbook_dir }}/temp/k0sctl.yaml"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Check if /home/????/.local/bin/k0sctl exists
      ansible.builtin.stat:
        path: "{{ user_info.home }}/.local/bin/k0sctl"
      changed_when: false
      register: k0sctl_bin

    - name: Install k0sctl
      ansible.builtin.shell: |
        wget {{ k0sctl_download_url }}
        mv {{ playbook_dir }}/temp/k0sctl-linux-amd64 {{ user_info.home }}/.local/bin/k0sctl
        chmod +x {{ user_info.home }}/.local/bin/k0sctl
      args:
        chdir: "{{ playbook_dir }}/temp"
        executable: /bin/bash
      when: not k0sctl_bin.stat.exists

    - name: Setup nodes with k0sctl
      block:
          #  ssh: handshake failed ? ssh-keygen -R [ipv4] and ssh [ipv4]
        - name: Setup nodes with k0sctl
          ansible.builtin.shell: |
            k0sctl apply --config k0sctl.yaml
          args:
            chdir: "{{ playbook_dir }}/temp"
            executable: /bin/bash
      rescue:
        - name: Setup nodes with k0sctl
          ansible.builtin.shell: |
            ssh-keygen -R {{ hostvars[item].network.ipv4 }}
          with_items: "{{ groups['k0s'] }}"

    - name: Get config values
      ansible.builtin.shell: |
        k0sctl kubeconfig admin --config k0sctl.yaml
      args:
        chdir: "{{ playbook_dir }}/temp"
        executable: /bin/bash
      register: kubeconfig

    - name: Print kubeconfig
      ansible.builtin.debug:
        msg: "{{ kubeconfig.stdout_lines }}"
