network:
  version: 2
  ethernets:
    {{ network.interface }}:
      dhcp4: no
      addresses:
        - {{ network.ipv4 }}/24
      routes:
        - to: default
          via: 192.168.8.1
      nameservers:
        addresses:
          - 192.168.8.1
          - 8.8.8.8
          - 8.8.4.4
