network:
  version: 2
  ethernets:
    {{ network.interface }}:
{% if network.e1000e is defined and network.e1000e %}
      # bug fix for Server kernel: e1000e 0000:00:19.0 eno1: Detected Hardware Unit Hang:
      generic-segmentation-offload: false
      tcp-segmentation-offload: false
{% endif %}
      dhcp4: no
      addresses:
        - {{ network.ipv4 }}/24
      routes:
        - to: default
          via: 192.168.8.1
      nameservers:
        addresses:
          - 192.168.8.1
          - 8.8.8.8
          - 8.8.4.4
