agent:
  defaultsProviderTemplate: default
  image:
    repository: "jenkins/inbound-agent"
    tag: "latest" # default has no riscv64 support, latest has!
controller:
  admin:
    username: opvolger
    password: demodemo
  sidecars:
    configAutoReload:
      image:
        repository: opvolger/k8s-sidecar
        tag: 2.7.3-4
      imagePullPolicy: IfNotPresent
  ingress:
    enabled: true
    hostName: "jenkins.k8s.opvolger.eu"
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - blueocean:latest
    - job-dsl:latest
  JCasC:
    configScripts:
      jobs: |
        jobs:
          - script: >
              pipelineJob('test') {
                definition {
                  cps {
                    sandbox()
                    script("""\
                      pipeline {
                          agent {
                              kubernetes {
                                  yaml '''
                      apiVersion: v1
                      kind: Pod
                      spec:
                        containers:
                        - name: shell
                          image: ubuntu:24.04
                          command:
                          - sleep
                          args:
                          - infinity
                          securityContext:
                            runAsUser: 1000
                      '''
                                  defaultContainer 'shell'
                                  retries 2
                              }
                          }
                          stages {
                              stage('Main') {
                                  steps {
                                      sh 'uname -a'
                                  }
                              }
                          }
                      }""".stripIndent())
                  }
                }
              }
