---
controller:
  image:
    # pullPolicy: Always
    repository: opvolger/metallb-controller
    tag: v0.15.3
speaker:
  frr:
    enabled: false # no riscv64 (build)
  image:
    # pullPolicy: Always
    repository: opvolger/metallb-speaker
    tag: v0.15.3
