---
all:
  children:
    linux:
      hosts:
        nuc.cluster:
          ansible_host: 192.168.8.13 # first set this to dhcp address and run k0s_setup_network.yaml
          k8s:
            role: controller+worker
            k0sBinaryPath: /home/opvolger/k0s-amd64
            noTaints: true
          network:
            ipv4: 192.168.8.13
            interface: eno1
          arch: amd64
        rp5.cluster:
          ansible_host: 192.168.8.10 # first set this to dhcp address and run k0s_setup_network.yaml
          k8s:
            role: controller+worker
            k0sBinaryPath: /home/opvolger/k0s-arm64
            noTaints: true
          network:
            ipv4: 192.168.8.10
            interface: eth0
          arch: arm64
        rp3b.cluster:
          ansible_host: 192.168.8.11 # first set this to dhcp address and run k0s_setup_network.yaml
          k8s:
            role: worker
            k0sBinaryPath: /home/opvolger/k0s-arm64
          network:
            ipv4: 192.168.8.11
            interface: eth0
          arch: arm64
        sfvf2lite.cluster:
          ansible_host: 192.168.8.12 # first set this to dhcp address and run k0s_setup_network.yaml
          k8s:
            role: controller+worker
            k0sBinaryPath: /home/opvolger/k0s-riscv64
            noTaints: true
            environment:
              ETCD_UNSUPPORTED_ARCH: riscv64
          network:
            ipv4: 192.168.8.12
            interface: end0
          arch: riscv64
    samba:
      hosts:
        nuc.cluster:
          sambaPassword: Ab12345!
    k0s:
      hosts:
        nuc.cluster:
        rp5.cluster:
        rp3b.cluster:
        sfvf2lite.cluster:
