---
all:
  children:
    ungrouped:
      hosts:
        localhost:
          k0sctl_download_url: https://github.com/k0sproject/k0sctl/releases/download/v0.32.1/k0sctl-linux-amd64
          ansible_connection: local
    riscv64:
      hosts:
        sfvf2lite.cluster:
        sfvf2lite2.cluster:
    linux:
      vars:
        k0s_binary_path_without_arch: /home/opvolger/Downloads/k0s-v1.37.0-alpha.1+k0s.0-
        helm_version: v4.2.2
      hosts:
        rp5.cluster:
          ansible_host: 192.168.8.10 # first set this to dhcp address and run k0s_setup_network.yaml
          k8s:
            role: controller+worker
            noTaints: true
          network:
            ipv4: 192.168.8.10
            interface: eth0
        rp3b.cluster:
          ansible_host: 192.168.8.11 # first set this to dhcp address and run k0s_setup_network.yaml
          k8s:
            role: worker
          network:
            ipv4: 192.168.8.11
            interface: eth0
        sfvf2lite.cluster:
          ansible_host: 192.168.8.12 # first set this to dhcp address and run k0s_setup_network.yaml
          k8s:
            role: controller+worker
            noTaints: true
            environment:
              ETCD_UNSUPPORTED_ARCH: riscv64
          network:
            ipv4: 192.168.8.12
            interface: end0
        nuc.cluster:
          ansible_host: 192.168.8.13 # first set this to dhcp address and run k0s_setup_network.yaml
          k8s:
            role: controller+worker
            noTaints: true
          network:
            e1000e: true
            ipv4: 192.168.8.13
            interface: eno1
        supermicro.cluster:
          ansible_host: 192.168.8.14 # first set this to dhcp address and run k0s_setup_network.yaml
          k8s:
            role: worker
          network:
            ipv4: 192.168.8.14
            interface: eno1
        sfvf2lite2.cluster:
          ansible_host: 192.168.8.15 # first set this to dhcp address and run k0s_setup_network.yaml
          k8s:
            role: worker
            environment:
              ETCD_UNSUPPORTED_ARCH: riscv64
          network:
            ipv4: 192.168.8.15
            interface: end0
    samba:
      hosts:
        nuc.cluster:
          samba_password: Ab12345!
    k0s:
      hosts:
        nuc.cluster:
        rp5.cluster:
        rp3b.cluster:
        sfvf2lite.cluster:
        supermicro.cluster:
        sfvf2lite2.cluster:
