- name: Permit 192.168.8.x traffic
  ansible.posix.firewalld:
    zone: trusted
    source: "{{ hostvars[item].ansible_host }}"
    permanent: true
    state: enabled
  notify: Reload firewalld
  loop: "{{ groups['k0s'] }}"

# after trusted network for all nodes, maybe i need less ports open on the nodes it self?

- name: Permit tcp
  ansible.posix.firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
  notify: Reload firewalld
  loop:
    - 2380 # traffic etcd
    - 6443 # traffic kube-apiserver
    - 179  # traffic kube-router
    - 7946 # MetalLB speakers for leader election and memberlist gossip
    - 7472 # Permit 7472/tcp MetalLB for metrics (used for readiness/liveness checks)
    - 10250 # kubelet
    - 9443 # k0s api
    - 8132 # konnectivity
    - 112 # keepalived
    - 2379 # etcd server
    - 2380 # etcd peer communication
    - 9100 # traefik METRICS
    - 8080 # traefik TRAEFIK
    - 8000 # traefik WEB
    - 8443 # traefik WEBSECURE

- name: Permit udp
  ansible.posix.firewalld:
    port: "{{ item }}/udp"
    permanent: true
    state: enabled
  notify: Reload firewalld
  loop:
    - 7946 # MetalLB speakers for leader election and memberlist gossip
    - 4789 # traffic calico
    - 17500 # metrics-server

- name: Permit 10.x cluster traffic
  ansible.posix.firewalld:
    zone: trusted
    source: 10.0.0.0/8
    permanent: true
    state: enabled
  notify: Reload firewalld

- name: Enable a firewalld
  ansible.builtin.systemd_service:
    name: firewalld
    state: started
    enabled: true
