- name: Permit 137/udp traffic samba
  ansible.posix.firewalld:
    port: 137/udp
    permanent: true
    state: enabled
  register: permit137

- name: Permit 138/udp traffic samba
  ansible.posix.firewalld:
    port: 138/udp
    permanent: true
    state: enabled
  register: permit138

- name: Permit 139/tcp traffic samba
  ansible.posix.firewalld:
    port: 139/tcp
    permanent: true
    state: enabled
  register: permit139

- name: Permit 445/tcp traffic samba
  ansible.posix.firewalld:
    port: 445/tcp
    permanent: true
    state: enabled
  register: permit445

- name: Always reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  when: permit137.changed or
        permit138.changed or
        permit139.changed or
        permit445.changed

- name: Enable a firewalld
  ansible.builtin.systemd_service:
    name: firewalld
    state: started
    enabled: true
