- name: Update repositories cache and upgrade package
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
    autoremove: true

- name: Installed some stuff 1
  ansible.builtin.apt:
    name:
      - wget
      - tar
      - systemd-resolved
      - procps
      - kubectl
      - gpg
      - curl
      - apt-transport-https
      - python3-kubernetes
      - python3-firewall
      - firewalld
      - netplan.io
    state: present

- name: Get DEB architecture
  ansible.builtin.shell: dpkg --print-architecture
  changed_when: false
  register: deb_architecture

- name: Check version of helm (if installed)
  ansible.builtin.shell: "helm version | grep {{ helm_version }}"
  register: version_check
  changed_when: false
  # grep will exit with 1 when no results found.
  # This causes the task not to halt play.
  ignore_errors: true

- name: Install Helm
  ansible.builtin.shell: |
    wget https://get.helm.sh/helm-{{ helm_version }}-linux-{{ deb_architecture.stdout }}.tar.gz
    tar -zxvf helm-{{ helm_version }}-linux-{{ deb_architecture.stdout }}.tar.gz
    mv linux-{{ deb_architecture.stdout }}/helm /usr/local/bin/helm
  args:
    executable: /bin/bash
  changed_when: true
  when: version_check.rc != 0
