apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
  user: admin
spec:
  hosts:
  # https://serverfault.com/questions/160581/how-to-setup-passwordless-sudo-on-linux
  - ssh:
      address: 192.168.8.13
      user: opvolger
    role: worker
    k0sBinaryPath: /home/opvolger/k0s-amd64
  - ssh:
      address: 192.168.8.10
      user: opvolger
    role: controller+worker
    k0sBinaryPath: /home/opvolger/k0s-arm64
    noTaints: True
  - ssh:
      address: 192.168.8.11
      user: opvolger
    role: controller+worker
    k0sBinaryPath: /home/opvolger/k0s-arm64
    noTaints: True
  - ssh:
      address: 192.168.8.12
      user: opvolger
    role: controller+worker
    k0sBinaryPath: /home/opvolger/k0s-riscv64
    noTaints: True
    environment:
      ETCD_UNSUPPORTED_ARCH: riscv64
  k0s:
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        # images:
        #   calico:
        #     cni:
        #       image: quay.io/k0sproject/calico-cni
        #       version: v3.29.7-1
        #     node:
        #       image: quay.io/k0sproject/calico-node
        #       version: v3.29.7-1
        #     kubecontrollers:
        #       image: quay.io/k0sproject/calico-kube-controllers
        #       version: v3.29.7-1
        api:
          externalAddress: 192.168.8.1
          k0sApiPort: 9443
          port: 6443
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        extensions:
          helm:
            repositories:
            - name: prometheus-community
              url: https://prometheus-community.github.io/helm-charts
            - name: traefik
              url: https://traefik.github.io/charts
            - name: metallb
              url: https://metallb.github.io/metallb
            charts:
            # docker buildx build --platform linux/amd64,linux/arm64,linux/riscv64 --tag opvolger/metallb-controller:v0.15.3  --push --file controller/Dockerfile .
            # docker buildx build --platform linux/amd64,linux/arm64,linux/riscv64 --tag opvolger/metallb-speaker:v0.15.3  --push --file speaker/Dockerfile .
            # helm install metallb metallb/metallb --values templates/metallb.yaml -n metallb-system
            # helm uninstall metallb -n metallb-system
            # kubectl apply -f templates/ip-pool.yaml -n metallb-system
            # https://oneuptime.com/blog/post/2026-02-09-kube-proxy-strict-arp-metallb/view
            - name: metallb
              chartname: metallb/metallb
              version: 0.15.3
              namespace: metallb-system
              values: |
                controller:
                  image:
                    # pullPolicy: Always
                    repository: opvolger/metallb-controller
                    tag: v0.15.3
                speaker:
                  frr:
                    enabled: false # no riscv64 (build)
                  image:
                    # pullPolicy: Always
                    repository: opvolger/metallb-speaker
                    tag: v0.15.3
            # helm install traefik traefik/traefik --values templates/traefik.yaml -n traefik-system --version 39.0.7
            # helm uninstall traefik -n traefik-system
            # https://oneuptime.com/blog/post/2026-01-07-metallb-traefik-ingress/view
            - name: traefik
              chartname: traefik/traefik
              version: 39.0.7
              namespace: traefik-system
              values: |
                service:
                  enabled: true
                  annotations:
                    # Request a specific IP from MetalLB's pool
                    metallb.universe.tf/loadBalancerIPs: "192.168.8.50"
            concurrencyLevel: 5
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          calico:
            mode: vxlan
          kubeProxy:
            disabled: false
            mode: iptables
          ipvs:
            strictARP: true
          kuberouter:
            autoMTU: true
            mtu: 0
            peerRouterASNs: ""
            peerRouterIPs: ""
          podCIDR: 10.244.0.0/16
          provider: kuberouter
          serviceCIDR: 10.96.0.0/12
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        storage:
          type: etcd
        telemetry:
          enabled: false
  options:
    wait:
      enabled: false # raspberry pi 3 is slow! timeout
    drain:
      enabled: true
      gracePeriod: 2m0s
      timeout: 5m0s
      force: true
      ignoreDaemonSets: true
      deleteEmptyDirData: true
      podSelector: ""
      skipWaitForDeleteTimeout: 0s
    concurrency:
      limit: 30
      workerDisruptionPercent: 10
      uploads: 5
    evictTaint:
      enabled: false
      taint: k0sctl.k0sproject.io/evict=true
      effect: NoExecute
      controllerWorkers: false
